### ISSUE TITLE
NextCloud Support?

### ISSUE THREAD

**Issue by uhlhosting** [aaronpk/Overland-iOS#101]
Hi,

Any plans to add nextcloud support ? Simillar to https://gitlab.com/eneiluj/phonetrack-oc .

**Comment by f8full** [comment]
Not that I can reply in the name of the author, but having another project myself I can say Nextcloud integration is a pain because they use non standard login mechanism. The cost of such integration is then super high, as well as the risks. On top of that, their support will treat you like dirt if you ask them questions about it.

**Comment by aaronpk** [comment]
I agree, I haven't had a great experience interacting with them on GitHub or elsewhere. I do run NextCloud myself, but I don't use phonetrack with it. I'd be more interested in adding Home Assistant support in any case, since you can do a lot more cool stuff with HA anyway. 

You could always set up a proxy script on shared hosting or on your nextcloud server that accepts the payload Overland sends and converts it and sends it to Nextcloud. That's actually how I push my location from Overland into my Home Assistant server.

Hope this helps!

**Comment by trajano** [comment]
I wonder if it can be done using webhooks API provided by NextCloud
