### ISSUE TITLE
Is it possible to make an option to ditch the new-received location/point when it is too near to the last one logged?

### ISSUE THREAD

**Issue by eMous** [aaronpk/Overland-iOS#117]
Hi!

I am using this app to log my locations everyday unremittingly with the phonetrack nextcloud as a server.  I have set the mode to `Significant Only`, in general, as long as I am moving, it works perfectly for me. 

But as long as I stay in an area(like home), for even a short period, it still continuously posts the location points to the server. And the "Automatic Pause" is not that reliable that its notification may vary from 1 hour to many hours to show, which means everyday I may get more than almost 10 thousands points which only indicate I am at home.  Like the image below, I think if I didn't ditch the useless points manually on the server part, the rendering and filtering job may very soon meet trouble.

<img width="444" alt="image" src="https://user-images.githubusercontent.com/33351631/160547166-675ef871-fda0-47ee-9114-43bf57a453e4.png">

So is it possible to setup an option in the setting page that user can input an appropriate distance between the new-received location and the last logged/posted location and if the current location is considered too near to the last one, then just don't write it to the local database or don't post it to the server?

This may be related to #96, but I think "how often" is not the key, because when I am moving all the data would be meaningful, even it is at 1 point/sec freqency. But when the user stays it should prevent flooding meaningless locations.

Thanks!

**Comment by aaronpk** [comment]
That's a reasonable feature request, I'll see what I can do!

But I'm surprised you're getting that kind of data with the "significant only" setting enabled!

**Comment by eMous** [comment]
It is weird to me as well, since I use OwnTracks with the Significant mode as well and everything is OK if I use that app instead of the its logging density is quite low for me.

FYI, if it is useful, it is an iPhone XS device in iOS15.3.1. For the same trip, I got  35 points from that app, but 7378 points from Overland today.

**Comment by Zacho2** [comment]
I'm also experiencing this issue. The queue increases as soon as the phone is no longer stationary whether significant location is enabled or only.

**Comment by aaronpk** [comment]
Interesting, sounds like something changed internally in iOS then! This is definitely worth creating a setting to filter this out.

The one downside to a setting like this is if you have a "minimum change distance" of say 100 meters, then it would _always_ ignore points closer together than 100m even when you're moving. I can't think of a simple way to tell the difference between noisy data at approximately the same location vs intentional movement. Any suggestions are welcome though.

**Comment by oe8bck** [comment]
Sorry to ask a maybe stupid question in this topic, but this is the result when I searched for topics with my problem.

If I get it correctly, @eMous is using Overland-iOS with the [Nextcloud App PhoneTrack](https://apps.nextcloud.com/apps/phonetrack). This is exactly what I also would like to do, but how to setup the connection correctly? Which one of [these methods](https://gitlab.com/eneiluj/phonetrack-oc/-/wikis/userdoc#logging-methods) is the correct one?

Thanks for any hint!
KR,
Christof

**Comment by momonala** [comment]
Hi! Would just like to bump this issue as Im having the same one. The other issue this presents is that it eats into my battery - on average 30-60% battery usage overnight when Im sleeping. Its a bit unpredictable (a few nights its been as low as 10). 

Regarding this: 
> The one downside to a setting like this is if you have a "minimum change distance" of say 100 meters, then it would always ignore points closer together than 100m even when you're moving. I can't think of a simple way to tell the difference between noisy data at approximately the same location vs intentional movement. Any suggestions are welcome though.

What about using the IMU/accelerometer as a switch - if movement is below some threshold then dont log points. Put it into a sleep mode, and poll for movement every 30-60 seconds. If there is movement, then start polling the GPS every second as normal. When movement dies down again, increase the movement polling wait-time. Is something like that reasonable to implement? Or is it difficult to bring in the IMU API? Would offer help but Im not very knowledgeable about iOS/swift unfortunately.

**Comment by aaronpk** [comment]
This is added and will go out in the next App Store update.

Please note that this will not have a dramatic effect on battery life, since the location data will already have been sent to the app by the time the app decides to discard it. It should only be used if you want to avoid a noisy cluster of points at home. That said, you might still get some noisy data at home because if your GPS error is more than the distance set, it will still jump out and back to your house. Play around with the other settings in the app to filter it at the OS level instead of the app level.
