### ISSUE TITLE
iOS 16.4.1 - no longer tracks in background

### ISSUE THREAD

**Issue by momonala** [aaronpk/Overland-iOS#122]
Hello! First off, thanks for the awesome app. I recently updated my iPhone 13 to iOS 16.4.1. Since then, Overland is no longer collecting data in the background. If I have the app on in the foreground, I collect one data point per second, as I always have. But if I close the phone or the app, ride my bike around, no new points are collected. Previously, I would always collect points at about 1 point/second while moving. I still get the location icon on the top bar when the app is closed, but its white and not blue. 

I double checked my security settings, and "allow location access" is set to always, and precise location is on. Attached are my app settings (high res profile). 

Any ideas on what could have changed? Hopefully its a configuration issue and not an app or security issue. 
![IMG_4190](https://user-images.githubusercontent.com/16393105/232763129-1923964f-cb92-4d48-b9ce-3f98885a24c7.PNG)

**Comment by iamchrishckns** [comment]
I was facing the same issue. I searched around a bit and found a article describing the issue. I don't have the article on hand right now but it had something to do with how "significant location" updates are handled.

When I disabled the "significant location" option I received all location data in the background again.

**Comment by lostfocus** [comment]
I tried that this morning and my phone immediately started heating up. It's all a bit weird since the last iOS update.

**Comment by aaronpk** [comment]
Looks like we're going to need to make some changes for the latest iOS version, as described here:

https://developer.apple.com/forums/thread/726945

**Comment by aaronpk** [comment]
Yes, I am planning to update it, but it's been a few years since I've compiled it so I need to make it compile in the latest XCode again: #124

**Comment by naibed2000** [comment]
hello, with iOS 17 now released, do you have any news on overland update? I really miss it :(

**Comment by gedankenstuecke** [comment]
I'd been wondering about the issue too and just saw that this has been already reported! @aaronpk is there anything that we could do to help? 🙂

**Comment by aaronpk** [comment]
So I'm confused here because I'm still running this app on my phone, updated to iOS 17, and it's fine. But I might be using different settings that others here. Can you share what settings you have it at that's causing the app to shut off in the background? Here are my settings.  

![IMG_2111](https://github.com/aaronpk/Overland-iOS/assets/113001/aef69654-b342-4de9-9598-83dd2deb12dd)

anyway, if anyone has iOS development experience, the first thing I need to do with this is to get it to build in the latest version of XCode, I'm guessing there will be a handful of dependencies to update and probably some syntax changes and UI updates. Any help with that would be appreciated!

**Comment by gedankenstuecke** [comment]
Thanks @aaronpk, I've tried adapting my settings to yours and will see how that works out. The changes I made were disabling "Significant location", which was set to enabled and is now disabled and "resume with geofence". 

According to the docs I'd have guessed that if anything both of these should improve sampling frequency, but I'll keep you updated! :)

**Comment by aaronpk** [comment]
I've just made a bunch of changes to support the new permissions model in iOS 16/17. This will go out in the next update in the App Store: #41

**Comment by dontic** [comment]
@aaronpk I've had the same issue since iOS16.4 (https://developer.apple.com/forums/thread/726945). But testing version 1.3 on iOS 17.1.1 yields the same results.

Worth noting that I thought it may be my iPhone (iPhone 11 pro), but then I checked other apps that use the location in the background: such as Home Assistant or Danalock and they work completely fine.

I've recently been on a trip so I took advantage to test this further.

### Preparation:

- I had the same settings as yours in https://github.com/aaronpk/Overland-iOS/issues/122#issuecomment-1801715015, but with "Pause Updates Automatically" active (**I will be testing this week with this setting off and post an update**).
- Ensured notifications were active.
- Ensured location permissions are set to allow always.


### Findings:

- I noticed I wasn't receiving "resumed" or "paused" notifications consistently.
- When I did not get "resumed" notifications after a while on the move, I would open the app and immediately get the "resumed location updates" notification and see the app logging locations every second consistently.
- After closing the app again the location updates would stop without notification again.
- This behavior is independent from having the app completely closed (slide up) or having it in the background.

### iOS 17.1.1 Nov 2023 active testing
![image](https://github.com/aaronpk/Overland-iOS/assets/25914304/74d7bcd6-ddcf-43c2-99cd-72aef0381467)

### iOS 17.1.1 Nov 2023 active testing
![image](https://github.com/aaronpk/Overland-iOS/assets/25914304/2ba6e649-8529-40da-b7a5-2f5c110bc264)


### iOS 17.1.1 Nov 2023 pasive testing
Leaving the app in the background
![image](https://github.com/aaronpk/Overland-iOS/assets/25914304/3453f9ed-353e-4798-a83d-5807b5d3a95c)


### iOS ? Jan 2023
App closed
![image](https://github.com/aaronpk/Overland-iOS/assets/25914304/53b42330-6fd1-43d7-b676-a301a68c9fa0)

**Comment by gedankenstuecke** [comment]
The "updates automatically" seems indeed to be the issue, I changed the options as outlined above and it works fine again!

**Comment by aaronpk** [comment]
Yes, I am reasonably confident the new beta version is working now, I've been running it myself for a few weeks. I'm going to push this out to the app store shortly.
