### ISSUE TITLE
apiAccessToken

### ISSUE THREAD

**Issue by protrakit** [aaronpk/Overland-iOS#123]
Looking through the code, it looks like there should be a text field to input the token. But, I'm not seeing this field in the app. I can't send a POST without having this header added. I tried adding the query param "token" in the url, but that doesn't help either. And it doesn't look like you're pulling that parameter out of the url to apply it to the header.

Any suggestions?

Also, when trying to use the app link to open the app and apply the setup, it doesn't work as well.

**Comment by aaronpk** [comment]
I'm so sorry, this is in the current code but I still haven't yet released the latest version to the app store!

I need to get an update out ASAP though because of some changes in iOS 16 and 17.

**Comment by aaronpk** [comment]
You can build the app yourself and install it on your own devices using a developer account without publishing it to the app store, but you still need the $99/yr developer account to do that. I've been paying that this whole time just to have this app in the app store and I really need to do an update to actually get these fixes out!

If you're interested in helping, I could definitely use some help getting this updated and building in the latest XCode version, since the last one I built it with is a few years out of date and I'm sure there are going to be some things that don't build in the latest version.

That said, I don't expect that to be an easy task at all for someone who has never done iOS development before.

**Comment by protrakit** [comment]
I'd love to help! I'm very good at geospatial programming. I've built a SaaS that I'm trying to test this functionality of it (having a tracker POST to my server) and instead of buying a GPS Tracker right away, I knew I'd find something that could allow me to test in the mean time.

I went the easy route and I'm using MongoDB Atlas/Realm, which is AWESOME for web app dev and geo data. I could definitely help on the app functionality and what not, but as far as coding goes, I can really only go through and find things that seem out of line or missing. haha

**Comment by aaronpk** [comment]
Thank you! The first step is to just get this building in XCode 15. I created an issue to track that: #124 

I will also admit that while this is a location-based app, most of the magic is handled by iOS, so this is mostly an exercise in figuring out the intricacies of Apple's APIs rather than solving interesting geospatial problems 😅

**Comment by protrakit** [comment]
Will NOT upgrading to 15 cause issues with the current app? If not, I would honestly focus on the updates in the current format/version you're in and then upgrade from that. Just my opinion though.

I completely understand that this is more of a "device location app" and not a "geospatial type app". But, they do go hand in hand as it's location based. I'm here to help anyway I can! I think what you have is awesome and there's not really any other apps that focus on the simplistic design and functionality. The biggest functionality is sending to an http url. That's dope! Plus the batch post and interval is a great idea, which is what I'm focused on.

I was able to do a work around and I have it working at the moment. Im seeing a few areas that could be enhanced pertaining to the way it processes the data and sends to the server.

Would you like me to create issues or just send a message?

**Comment by aaronpk** [comment]
Cool, definitely happy to get suggestions for improvements! Go ahead and file new issues for them so we can track them!

> Will NOT upgrading to 15 cause issues with the current app? If not, I would honestly focus on the updates in the current format/version you're in and then upgrade from that. Just my opinion though.

Normally I'm 100% with you there, but unfortunately that's not really how it works in the Apple world. I'd have to find an old laptop with an old MacOS in order to install an old XCode in order to publish a version that isn't built with the latest XCode. That's why step 1 of any of this is to just get it to build in the latest version, then work on the more significant location API changes to make sure it still works in the background all the time.

**Comment by protrakit** [comment]
Of course Apple would do that! haha. Well, unfortunately I'm not able to help on that side of it, but I can submit issues with what I'm currently experiencing. I hope you're able to upgrade this and keep the project moving forward! I'll help as much as I can and thanks for all you've done!

**Comment by aaronpk** [comment]
This is building in XCode 15, so I'm close to being able to publish an update to the App Store. Tracking that here: #41
