### ISSUE TITLE
Multiple Enhancements

### ISSUE THREAD

**Issue by protrakit** [aaronpk/Overland-iOS#125]
- Tracker
1. Add a button to reset the queue and delete stored locations.
2. When tracking has started, create a random ID for that tracking session. Add that session ID to the details when sent to the server. This will help managing that entire session when adding to DB.
3. When tracking has started, change the Send Now button to "Tracking" or something else and maybe disable it or change color
4. The Last Sent is showing Hours : Minutes, but below it says "minutes ago". Just show totals minutes without the hours

- Settings
1. If I turn on Tracking Enabled, it won't send locations to the server when starting a track. You have to turn it off and then it will work. Took me a minute to realize that. Maybe move this option to the Tracker view beside the Send Now button or something. If it's marked as OFF, then disable the Send Now button.

- Endpoint URL
1. Add the API Key text field, which will be added to the header as a Bearer
2. Separate the URL field into a HOST field and PATH field. Then join the two together in the code. This will make it easier to change paths and manage long urls
3. Make the Device ID field disabled and auto populate with the actual device id or ip address or something unique to that device
5. Add a User ID field that can act like the current Device ID field, which is a custom input value

**Comment by aaronpk** [comment]
> Add a button to reset the queue and delete stored locations.

Already requested: #78 

> When tracking has started, create a random ID for that tracking session. Add that session ID to the details when sent to the server. This will help managing that entire session when adding to DB.

Good idea, opening as a new issue: #129

> When tracking has started, change the Send Now button to "Tracking" or something else and maybe disable it or change color

I don't understand why you would want this, since the "Send Now" button works regardless of whether there is an active trip.

> The Last Sent is showing Hours : Minutes, but below it says "minutes ago". Just show totals minutes without the hours

It actually starts by showing "Minutes : Seconds", then changes to "Hours : Minutes" after an hour. It would be more accurate to change the labels to say "hours ago" instead of "minutes ago".

> If I turn on Tracking Enabled, it won't send locations to the server when starting a track.

This is not how it's supposed to work, I suspect you're encountering the issues with the new iOS 16/17 location permissions. Once "Tracking Enabled" is turned on, you should always be getting updates added to the queue, at least as long as you have the rest of the settings configured to enable background updates.

> Add the API Key text field, which will be added to the header as a Bearer

This is in the latest version but not published to the app store yet

> Separate the URL field into a HOST field and PATH field

There is an option to launch the app from a custom URL that can make configuring this easier if you're managing multiple devices: https://github.com/aaronpk/Overland-iOS#configuration-by-custom-url

> Make the Device ID field disabled and auto populate with the actual device id or ip address or something unique to that device

There is a new setting in the iOS Settings screen to include the device's Unique ID. The "Device ID" in the app is still for the user-entered value.

> Add a User ID field that can act like the current Device ID field, which is a custom input value

See above
