### ISSUE TITLE
Include course in location data

### ISSUE THREAD

**Issue by ipearx** [aaronpk/Overland-iOS#146]
Hi I just noticed the current course/direction isn't included in the output data for each location point.

This is useful for drawing icons on a map for example in the right direction. Currently in PureTrack for example I have to draw the icons pointing straight up, compared to tracking data from other sources.

![Screenshot 2023-12-28 at 7 12 58 PM](https://github.com/aaronpk/Overland-iOS/assets/1772008/a19728c3-6730-4203-9dd1-c922155f5ba3)

It might seem like you can simply figure it out from the last point but this doesn't work for the first point, or if there are big gaps in the data.

Course is included in iOS's location data, along with speed and altitude.
Was there any reason it wasn't included?

**Comment by aaronpk** [comment]
huh, I'm not sure why this isn't captured in the data! Definitely not intentional. My only thought is that maybe in the first version of this library, back in 2011 or so, the course data was so inaccurate that it was useless. Anyway I've just added it to the latest beta build so it will go out in the next release!
