### ISSUE TITLE
Dev compilation instructions not working

### ISSUE THREAD

**Issue by clarkezone** [aaronpk/Overland-iOS#149]
Following the instructions to build project locally (after forking), I'm getting this build error which looks like a missing file and or missing step in the instructions.  Not familiar with Pods, any ideas?

<img width="254" alt="Screenshot 2024-04-07 at 9 04 22 AM" src="https://github.com/aaronpk/Overland-iOS/assets/1128250/30215242-e67c-42f9-a273-63909e626e99">

**Comment by momonala** [comment]
I got this issue when I tried building from source a few weeks ago as well, would love to hear a solution on this! Not really a strong iOS developer so not sure where to start, but I couldnt find any good leads from a quick google search.

**Comment by aaronpk** [comment]
This was after running `pod install` and opening the workspace file?

https://github.com/aaronpk/Overland-iOS?tab=readme-ov-file#development-setup

One thing that kept tripping me up when using Cocoapods was forgetting to open the xcworkspace file instead of the xcproject file. Make sure you open `Overland.xcworkspace`

**Comment by clarkezone** [comment]
Turns out the dev setup instructions don't mention the `pod install` step so for us SwiftPM types we tend to forget that ;-) PR submitted
