### ISSUE TITLE
How do I make it like Moves?

### ISSUE THREAD

**Issue by kellyfw** [aaronpk/Overland-iOS#75]
Hi. I'm a pretty non-technical person, and I've wandered on here practically by mistake. I adored Moves, and when it shut down I signed up for an app providing a similar service - which was initially free, but now it's requesting its backers pay big bucks for a subscription service. It frustrates me nearly to tears, because I can see that my phone is already doing what I want it to do: track my movements and activities.  (I've looked at so many apps to try to find one which will do what Moves did, but the only ones that come close are fitness apps that want to know how much water I drink!) I've downloaded the Overland app, and I can see that it can do everything I want it to do. But my current ability to create my own back end is zero. Do you have any suggestions for me?

**Comment by aaronpk** [comment]
I was also a fan of Moves, they did so much right! It's really a bummer they shut it down.

Unfortunately, I don't have a very good answer for you. Part of the reason this app is free is because it doesn't come with any place to store the data or any easy way for you to see it. Instead it relies on pointing the app at some other server that can collect and display the data. I did write an app that can be installed on a server that does that, but it's not nearly as good as Moves and also is kind of complicated to get running.

Sorry I can't be more help!

**Comment by kellyfw** [comment]
OK, thanks for your reply. I figured it must be complicated, because actually no-one seems to be able to create something that did what Moves did - at least, not without wanting a subscription fee per month.
