### ISSUE TITLE
Automatic pause does not get triggered consistently

### ISSUE THREAD

**Issue by martijnv-telenav** [aaronpk/Overland-iOS#79]
Perhaps this is just me misunderstanding the settings.
I have notifications on so I will sometimes get notified by Overland that location updates were paused, and then resumed when I exit the geofence. The pause notification I only get very infrequently. I am not sure if this is because the notification is not always sent or because the location updating does not actually get paused. Here are my settings:

![46352901044_2bbb6ff125_b](https://user-images.githubusercontent.com/15021381/52673976-7a8a9d00-2edf-11e9-9906-c87941f80d51.jpg)

I'm looking to reduce battery impact without sacrificing too much in the way of accuracy.

**Comment by aaronpk** [comment]
Welcome to the wild world of the black box that is Apple location services! 

Here is what Apple has to say about the setting:

https://developer.apple.com/documentation/corelocation/cllocationmanager/1620553-pauseslocationupdatesautomatical?language=objc

> Allowing the location manager to pause updates can improve battery life on the target device without sacrificing location data. When this property is set to YES, the location manager pauses updates (and powers down the appropriate hardware) at times when the location data is unlikely to change. For example, if the user stops for food while using a navigation app, the location manager might pause updates for a period of time. You can help the determination of when to pause location updates by assigning a value to the activityType property.

As most things in iOS, this is more of a suggestion to the location services than a boolean toggle. Turning this on "allows" the OS to pause updates, but does not guarantee it. For example if other apps are using your location and do not have this set, that may mean that the phone never pauses updates and Overland will just keep getting them since other apps are requesting updates anyway.

Unfortunately there isn't really any visibility into how this stuff works, so all I can say is that if you aren't seeing the notification, it's because Apple hasn't decided that it needs to pause updates, for some reason.

**Comment by mvexel** [comment]
(same person, different account)

I had a feeling this would be one of those things that's hard to really nail down.

A different idea to solve this: is it possible to detect whether you're connected to a specific wifi SSID (or one of a user defined list) and pause location updates if so?

That would allow users to add their home / work wifi and have location updates pause there, and resume as normal from geofence.

**Comment by aaronpk** [comment]
I *could* make it pause updates when it recognizes you're connected to a certain wifi name, but I wouldn't be able to guarantee that updates would resume again later.

The only way to resume the app once it's been paused is when iOS resumes the app from a geofence. There just isn't a way for this app to continually run code to check the connected wifi name to resume updates when it changes.

That said, if iOS isn't already pausing updates with that option checked, it's likely because some other app on the phone is still using updates so it just keeps delivering them to Overland. What I mean is that you probably wouldn't see any difference in battery life even if Overland did pause updates when connected to your wifi.
