### ISSUE TITLE
Throttling how much data is sent or setting a points time interval?

### ISSUE THREAD

**Issue by ipearx** [aaronpk/Overland-iOS#96]
Hi I've been using Overland for a bit for tracking flying gliders. The problem is the amount of data being sent to our servers and app, it would be good to reduce the number of points to one every 10 to 15 seconds. Currently it's doing 1 point per second.

"desired accuracy" is set to "best" which seems like the only control possible, but reading Apple's docs doesn't seem like the same thing i.e. it defines the required accuracy of a single point, not how often they happen? (I will test this more)

I noticed BTraced does have an option to set the interval between points, so it must be possible? I can imagine you can receive more GPS data on the device than is actually processed and sent to the server for example? i.e. some sort of throttle?

**Comment by aaronpk** [comment]
The controls Apple gives you don't provide any way to specify time interval between points. Like you found, "desired accuracy" will definitely affect how often data is collected. The idea is if your desired accuracy is 100 meters then you'd get a point only if the phone has moved about 100 meters. Of course it's nowhere near this precise in practice, in both directions.

I could definitely add another option in Overland which effectively discards any data received more often than X. It wouldn't affect battery life at all since iOS would still be delivering more frequent data to the app, but it would prevent the app from logging a point per second. (Actually the app already has this filter, it's just hard coded to 1 second, because believe it or not sometimes iOS sends data more often than that.)

**Comment by ipearx** [comment]
Hi just following up on this, great to see it is in the todo list. 
Yes what you suggested would be perfect, discard any data received more often than X. I've been playing around building my own app now that BTraced is no longer available to download on iOS, and that's what I'm doing. But would be great for people who want to use Overland with my tracking system, or on Android. I should deal with too much data on the server end too, but better to not transmit more data than needed in the first place! You can see what we're using it for here if you're interested:
http://gliding.net.nz/tracking
Cheers

**Comment by aaronpk** [comment]
Ok, this is in the app and will go out in the next App Store update!

Please note that this will not have a dramatic effect on battery life, since the location data will already have been sent to the app by the time the app decides to discard it. It should only be used if you want to reduce the overall amount of data sent to the server.

**Comment by ipearx** [comment]
Legend!  
PS. PureTrack isn't just for aircraft, you can use it to track anything. People also use it for boats, I have my van on it etc.
Cheers for the work
